### PR TITLE
Implement CUDA self-check binary

### PR DESCRIPTION
**Pull request by vnlitvinov**
When the `self-check` is run on a Linux system which has a CUDA device, its output should look like
```
Reported 1 CUDA devices
Device #0: name=NVIDIA GeForce RTX 3080: memory alloc test pass
all cards look ok
```
When it's run on a system where something is wrong, its output should reflect it, like
```
Cannot get device count: cuda error=35 - CUDA driver version is insufficient for CUDA runtime version
```

## Summary by CodeRabbit

- **New Features**
  - Introduced self-check functionality for CUDA devices, including device detection, memory allocation tests, and status reporting.
  - Added Docker support for running self-checks in a containerized environment.

- **Documentation**
  - Added a README with instructions for running the self-check binary on Linux or WSL2.

- **Chores**
  - Updated `.gitignore` to exclude build directories in the `self-check` directory.

### CODE REVIEW

**Review by ZhijieWang — CHANGES_REQUESTED** [review]
can we check how many lspci gets and how many nvidia-smi gets? Some time the device bios or boot driver fail.
if it is too difficult, create a linear ticket and check with Qin on roll out

**Comment by vnlitvinov** [comment]
For me, `lspci` and `nvidia-smi` are separate checks which talk to PCIe subsystem only, they don't try to actually interact with the CUDA driver or the device.

This `self-check` is tailored at specifically trying to do some very simple tasks on GPUs to ensure that driver and card are in at least somewhat sane state (e.g., it should hopefully help detect cases when people installed a driver, hence `nvidia-smi` reporting its version, but they haven't rebooted the box, so the driver doesn't actually _work_).

**Review by ZhijieWang — APPROVED** [review]
verified

**Review by smiraldr — APPROVED** [review]
LGTM

**Pull request merged**
